### PR TITLE
Prepare to implement framegraph

### PR DESCRIPTION
**Pull request by omni-viral**
This change is [Reviewable](https://reviewable.io/reviews/rustgd/rendy/5)

### CODE REVIEW

**Comment by omni-viral** [comment]
bors try

**Comment by torkleyy** [comment]
bors try

**Comment by torkleyy** [comment]
Seriously?

**Comment by torkleyy** [comment]
It seems to crash whenever I try to add you @omni-viral

**Comment by torkleyy** [comment]
now you're added, I don't think it works though

**Comment by torkleyy** [comment]
Oh, and don't we need a `bors.toml`?

**Comment by omni-viral** [comment]
It has defaults if `bors.toml` is absent

**Comment by omni-viral** [comment]
Okey. Let's see.
bors r+ please

**Pull request merged**
