### PR TITLE
Create bors.toml

### PR DESCRIPTION
**Pull request by torkleyy**

### CODE REVIEW

**Comment by torkleyy** [comment]
Ah thanks.

**Comment by torkleyy** [comment]
Please try again.

**Comment by torkleyy** [comment]
Great, experiments are done :)
bros r+

Now everything works the way you wanted it to @omni-viral

**Comment by Rhuagh** [comment]
bors r+

While bros are nice, I dont think bors recognise it ;)

**Comment by torkleyy** [comment]
lol :laughing:

**Pull request merged**
