### PR TITLE
Add version numbers to dependencies

### PR DESCRIPTION
**Pull request by magnonellie**

### CODE REVIEW

**Comment by omni-viral** [comment]
Bors r+

**Comment by magnonellie** [comment]
That was a quick build compared to what happens for the Amethyst repo :open_mouth:

**Comment by omni-viral** [comment]
Yeah. Amethyst takes some time to build.
Aren't tgere some caches to rebuild only crates with changes and their dependencies?

**Comment by magnonellie** [comment]
There are but they don't really work for Amethyst since they get so big. I think the plan is gonna be to move to Microsoft's Azure pipelines.

**Pull request merged**
